# Generated by Django 2.2.16 on 2023-07-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230706_1751'),
        ('reviews', '0003_auto_20230706_1646'),
    ]

    operations = [
    ]
