# Generated by Django 2.2.16 on 2023-07-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20230706_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'default_related_name': 'titles', 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterUniqueTogether(
            name='titlegenres',
            unique_together=set(),
        ),
    ]
