# Generated by Django 2.2.16 on 2023-07-10 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230706_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Только значения от 0 до 10'), django.core.validators.MaxValueValidator(10, 'Только значения от 0 до 10')], verbose_name='Рейтинг'),
        ),
    ]
